### ISSUE TITLE
Support passthrough in uat2json

### ISSUE THREAD

**Issue by mutability** [mutability/dump978#1]
Would be nice to have uat2json optionally write packets it reads to stdout, so you can put it midway through a pipeline.

**Comment by kevinelliott** [comment]
@mutability This is easily solved with `tee`.

**Comment by mutability** [comment]
Tee doesn't help with putting uat2json mid pipeline

**Comment by kevinelliott** [comment]
Yeah, you can pipe it to tee twice or more.

**Comment by mutability** [comment]
I think you miss the point; this issue was about being able to do

`dump978 | uat2json /some/path | uat2esnt`

or equivalent. You can't replicate that with tee and a single pipeline.

Mostly irrelevant now anyway as I'll be bulk-closing all issues on this repo soon in favor of new development on the FA fork (which isn't pipeline-oriented)

**Comment by kevinelliott** [comment]
Very confused. You most certainly can pipe it multiple times. I do it all the time.

```
    rtl_sdr -d 0 -f 978000000 -s 2083334 -g 48 - | /home/pi/dump978/dump978 | tee >(/home/pi/dump978/uat2json /var/www/html/dump978/data) | tee >(/home/pi/dump978/uat2esnt | /bin/nc -q1 adsb1.local 30001) | /home/pi/dump978/uat2text                                                                                                                                                                                                                                     
```

You can do it all you want. You can have tee push to log files (and then tail that in another terminal) and still keep the STDOUT chain, etc. I have one command that tees 5 times.

**Comment by mutability** [comment]
`>()` creates a second pipeline

**Comment by kevinelliott** [comment]
And the problem with that, is?

**Comment by mutability** [comment]
No problem, if you're OK with it being bash-specific and somewhat trickier to monitor. This issue was about making it simpler so you didn't need to jump through those hoops.

**Comment by mutability** [comment]
This isn't getting implemented anyway, closing the issue.

**Comment by kevinelliott** [comment]
Oh I see, I understand. My apologies for crossing wires on that.
