### ISSUE TITLE
Compilation errors in uat2esnt.c

### ISSUE THREAD

**Issue by aviatest** [mutability/dump978#12]
Environment notes:
GCC Version: 12.2.0
Linux Kernel: 6.0.0-1-MANJARO
GNU Make 4.3

When running `make`, I run into compiler errors regarding `esnt_frame` in `uat2esnt.c` possibly being uninitialized.

I attached the full log.
[output.txt](https://github.com/mutability/dump978/files/9463136/output.txt)

**Comment by mutability** [comment]
I'll take a PR to fix this but this code is otherwise unmaintained.
