### ISSUE TITLE
receiver.json isn't written (only the receiver.json.new file is written)

### ISSUE THREAD

**Issue by bakerkj** [mutability/dump978#5]
The code in write_receiver_json() never renames the receiver.json.new file to receiver.json.  Below is a patch that does.

---

 static int write_receiver_json(const char *dir)
 {
     char path[PATH_MAX];
-    char path_new[PATH_MAX];
   FILE *f;
-    if (snprintf(path, PATH_MAX, "%s/receiver.json.new", dir) >= PATH_MAX) {
-    if (snprintf(path, PATH_MAX, "%s/receiver.json", dir) >= PATH_MAX || snprintf(path_new, PATH_MAX, "%s/receiver.json.new", dir) >= PATH_MAX) {
       fprintf(stderr, "write_receiver_json: path too long\n");
       return 0;
   }
-    if (!(f = fopen(path, "w"))) {
-        fprintf(stderr, "fopen(%s): %m\n", path);
-    if (!(f = fopen(path_new, "w"))) {
-        fprintf(stderr, "fopen(%s): %m\n", path_new);
       return 0;
   }

@@ -200,6 +201,11 @@ static int write_receiver_json(const char *dir)
             "}\n");
     fclose(f);
-    if (rename(path_new, path) < 0) {
-        fprintf(stderr, "rename(%s,%s): %m\n", path_new, path);
-        return 0;
-    }
  +
   return 1;
  }

**Comment by mutability** [comment]
Good catch, thanks!
