### ISSUE TITLE
Has the JSON format for dump1090 changed?

### ISSUE THREAD

**Issue by fasiha** [mutability/dump978#7]
`uat2json` is producing `aircraft.json` containing the following object:

``` js
{now: 1472588074, 
 messages: 600,
 aircraft: [{"hex":"~28ce4b","lat":39.944272,"lon":-83.048680,"seen_pos":77,"altitude":900,"vert_rate":0,"track":24,"speed":95,"messages":1,"seen":77,"rssi":0}]}
```

But it looks like [dump1090](https://github.com/MalcolmRobb/dump1090) is looking for `data.json` which contains the following:

``` js
[{"hex":"4840cf", "squawk":"0000", "flight":"", "lat":0.000000, "lon":0.000000, "validposition":0, "altitude":38000,  "vert_rate":0,"track":0, "validtrack":0,"speed":0, "messages":8, "seen":3}]
```

It appears that dump1090’s frontend code only wants the inner `aircraft` slot from `uat2json`’s output.

I’d like your advice on how to approach this. I could modify dump1090, but since the dump978 project is making use of dump1090’s webserver, it’d seem that, for better maintainability, I should try changing `uat2json`?

**Comment by mutability** [comment]
Perhaps unsurprisingly, the format uat2json generates is what my fork of dump1090 expects, not the older fork you reference.

**Comment by fasiha** [comment]
Doh, now I see that the instructions advise cloning _your_ fork of dump1090—I feel so silly! Thanks!

Please consider the pull request to expand on the wording in the README.
